# Generated by Django 4.2.30 on 2026-05-07 22:03

import apps.responses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('texting', 'Texting'), ('live', 'Live'), ('live_voice', 'Live Voice')], max_length=20)),
                ('relationship_context', models.CharField(blank=True, max_length=50)),
                ('situation_summary', models.CharField(blank=True, max_length=200)),
                ('response_json', models.JSONField()),
                ('prompt_version', models.CharField(default='v2', max_length=10)),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_counts', models.JSONField(default=apps.responses.models.default_feedback_counts)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SavedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('safe', 'Safe'), ('playful', 'Playful'), ('bold', 'Bold')], max_length=20)),
                ('option_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='responses.airesponserecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('natural', 'Natural'), ('loved', 'Loved it'), ('cringe', 'Cringe'), ('risky', 'Too risky'), ('saved', 'Saved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='responses.airesponserecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'response_record', 'feedback_type')},
            },
        ),
    ]
