# Generated by Django 5.2.13 on 2026-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor_style', models.CharField(blank=True, choices=[('dry', 'Dry'), ('sarcastic', 'Sarcastic'), ('goofy', 'Goofy'), ('witty', 'Witty'), ('self_deprecating', 'Self-Deprecating'), ('observational', 'Observational'), ('dark', 'Dark'), ('absurd', 'Absurd')], default='', max_length=20)),
                ('persona_type', models.CharField(blank=True, choices=[('roaster', 'The Roaster'), ('storyteller', 'The Storyteller'), ('quick_wit', 'The Quick Wit'), ('charmer', 'The Charmer'), ('deadpan', 'The Deadpan')], default='', max_length=20)),
                ('confidence_level', models.CharField(blank=True, choices=[('shy', 'Shy'), ('moderate', 'Moderate'), ('confident', 'Confident'), ('fearless', 'Fearless')], default='', max_length=20)),
                ('cultural_tone', models.CharField(blank=True, choices=[('usa', 'United States'), ('canada', 'Canada')], default='', max_length=30)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
