# Generated by Django 5.2.13 on 2026-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personality_description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
