# Generated by Django 4.2.30 on 2026-05-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_add_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_anxiety_level',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('high', 'High')], default='mild', max_length=20),
        ),
    ]
